import type { PairingDeviceRole } from './pairing';

export interface DeviceLatest {
  v?: number;
  protocol?: 'wqm_ble_v2' | string;
  fw?: string;
  firmware_version?: string;
  fw_version?: string;
  schema_version?: number;
  device_id?: string;
  source_id?: string;
  role?: PairingDeviceRole;
  lifecycle_state?: string;
  link_state?: string;
  network_id?: string;
  parent_id?: string;
  root_gateway_id?: string;
  gateway_id?: string;
  current_hop_parent_id?: string;
  forwarded_by?: string;
  route?: string;
  ph?: number;
  td?: number;
  tds?: number;
  tm?: number;
  temp?: number;
  temperature?: number;
  tb?: number;
  turbidity?: number;
  bt?: number;
  battery?: number;
  rc?: number;
  tc?: number;
  fc?: number;
  kc?: number;
  seq?: number;
  sid?: number;
  rx_direct_count?: number;
  tx_packet_count?: number;
  forward_packet_count?: number;
  known_device_count?: number;
  direct_child_count?: number;
  gateway_upload_count?: number;
  own_upload_count?: number;
  source_rx_count?: number;
  source_tx_count?: number;
  source_forward_count?: number;
  source_known_count?: number;
  timestamp?: number;
  last_upload_ms?: number;
  last_seen_ms?: number;
  rssi?: number;
  snr?: number;
  child_rssi?: number;
  child_snr?: number;
  gateway_rssi?: number;
  gateway_snr?: number;
  wifi_connected?: boolean;
  wifi_ssid?: string;
  wifi_rssi?: number;
  ip?: string;
  switch_mode?: string;
  lora_ready?: boolean;
  lora_error?: string;
  lora_packet_count?: number;
  uptime_ms?: number;
  pair_confirmed?: boolean;
  telemetry_received?: boolean;
  waiting_for_first_data?: boolean;
  offline_firebase_queue_size?: number;
  offline_queue_ready?: boolean;
  forward_queue_size?: number;
  gateway_uplink_queue_size?: number;
  gateway_uplink_queue?: number;
  pairing_cloud_queue_size?: number;
  pairing_cloud_queue?: number;
}

export interface DeviceStatus {
  v?: number;
  protocol?: 'wqm_ble_v2' | string;
  fw?: string;
  firmware_version?: string;
  fw_version?: string;
  fw_seen_by?: string;
  schema_version?: number;
  device_id?: string;
  online?: boolean;
  role?: PairingDeviceRole;
  link_state?: string;
  parent_id?: string;
  root_gateway_id?: string;
  gateway_id?: string;
  current_hop_parent_id?: string;
  forwarded_by?: string;
  route?: string;
  network_id?: string;
  last_seen_ms?: number;
  updated_at?: number;
  last_upload_ms?: number;
  battery?: number;
  rssi?: number;
  snr?: number;
  child_rssi?: number;
  child_snr?: number;
  gateway_rssi?: number;
  gateway_snr?: number;
  seq?: number;
  sid?: number;
  rx_direct_count?: number;
  tx_packet_count?: number;
  forward_packet_count?: number;
  known_device_count?: number;
  direct_child_count?: number;
  gateway_upload_count?: number;
  own_upload_count?: number;
  source_rx_count?: number;
  source_tx_count?: number;
  source_forward_count?: number;
  source_known_count?: number;
  pair_stage?: string;
  pair_accepted?: boolean;
  pair_confirmed?: boolean;
  telemetry_received?: boolean;
  waiting_for_first_data?: boolean;
  lifecycle_state?: string;
  message?: string;
  command_stream?: string;
  wifi_connected?: boolean;
  wifi_ssid?: string;
  wifi_rssi?: number;
  ip?: string;
  switch_mode?: string;
  lora_ready?: boolean;
  lora_error?: string;
  lora_packet_count?: number;
  gateway_uplink_enabled?: boolean;
  relay_enabled?: boolean;
  offline_firebase_queue_size?: number;
  offline_queue_ready?: boolean;
  forward_queue_size?: number;
  forward_queue?: number;
  gateway_uplink_queue_size?: number;
  gateway_uplink_queue?: number;
  pairing_cloud_queue_size?: number;
  pairing_cloud_queue?: number;
  has_ever_paired?: boolean;
}

export interface NetworkDevice {
  id: string;
  latest: DeviceLatest | null;
  status: DeviceStatus | null;
  displayRole: PairingDeviceRole;
  online: boolean | null;
  lastSeenMs?: number;
  hasChildren?: boolean;
  source?: 'device' | 'pairingRequest';
}

export interface TopologyNode {
  device_id: string;
  role?: PairingDeviceRole;
  parent_id?: string;
  root_gateway_id?: string;
  depth?: number;
  route?: string;
  online?: boolean;
  last_seen_ms?: number;
  battery?: number;
  rssi?: number;
  snr?: number;
  pair_stage?: string;
  pair_confirmed?: boolean;
  telemetry_received?: boolean;
  lifecycle_state?: string;
  message?: string;
  children?: TopologyNode[];
}

export interface PairingTestRecord {
  test_id?: string;
  device_id?: string;
  parent_id?: string;
  root_gateway_id?: string;
  network_id?: string;
  role?: PairingDeviceRole;
  received_at?: number | string;
  status?: string;
  [key: string]: unknown;
}
